/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'payoutStatus' : { 'pending' : null } |
    { 'completed' : null } |
    { 'processing' : null },
  'payoutMethod' : PayoutMethod,
  'name' : string,
  'whatsapp' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'position' : string,
  'paymentIntentId' : string,
}
export type CreatePaymentResult = { 'ok' : { 'clientSecret' : string } } |
  { 'paymentError' : string } |
  { 'invalidAmount' : null };
export type PayoutMethod = { 'btc' : { 'address' : string } } |
  { 'giftCard' : { 'cardType' : string, 'email' : string } } |
  { 'paypal' : { 'email' : string } };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubmitApplicationResult = { 'ok' : null } |
  { 'submissionError' : string } |
  { 'duplicateApplication' : null } |
  { 'paymentNotFound' : null } |
  { 'missingFields' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPaymentIntent' : ActorMethod<[bigint], CreatePaymentResult>,
  'getApplications' : ActorMethod<[], Array<Application>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitApplication' : ActorMethod<
    [string, string, string, string, string, string, PayoutMethod],
    SubmitApplicationResult
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePayoutStatus' : ActorMethod<
    [
      string,
      string,
      { 'pending' : null } |
        { 'completed' : null } |
        { 'processing' : null },
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];