/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type PayoutMethod = {
    __kind__: "btc";
    btc: {
        address: string;
    };
} | {
    __kind__: "giftCard";
    giftCard: {
        cardType: string;
        email: string;
    };
} | {
    __kind__: "paypal";
    paypal: {
        email: string;
    };
};
export interface Application {
    payoutStatus: Variant_pending_completed_processing;
    payoutMethod: PayoutMethod;
    name: string;
    whatsapp: string;
    submittedAt: bigint;
    email: string;
    message: string;
    position: string;
    paymentIntentId: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type CreatePaymentResult = {
    __kind__: "ok";
    ok: {
        clientSecret: string;
    };
} | {
    __kind__: "paymentError";
    paymentError: string;
} | {
    __kind__: "invalidAmount";
    invalidAmount: null;
};
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type SubmitApplicationResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "submissionError";
    submissionError: string;
} | {
    __kind__: "duplicateApplication";
    duplicateApplication: null;
} | {
    __kind__: "paymentNotFound";
    paymentNotFound: null;
} | {
    __kind__: "missingFields";
    missingFields: null;
};
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    name: string;
}
export interface http_header {
    value: string;
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_completed_processing {
    pending = "pending",
    completed = "completed",
    processing = "processing"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createPaymentIntent(amount: bigint): Promise<CreatePaymentResult>;
    getApplications(): Promise<Array<Application>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitApplication(name: string, email: string, whatsapp: string, position: string, message: string, paymentIntentId: string, payoutMethod: PayoutMethod): Promise<SubmitApplicationResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updatePayoutStatus(email: string, position: string, newStatus: Variant_pending_completed_processing): Promise<boolean>;
}
import type { Application as _Application, CreatePaymentResult as _CreatePaymentResult, PayoutMethod as _PayoutMethod, StripeSessionStatus as _StripeSessionStatus, SubmitApplicationResult as _SubmitApplicationResult, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createPaymentIntent(arg0: bigint): Promise<CreatePaymentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createPaymentIntent(arg0);
                return from_candid_CreatePaymentResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPaymentIntent(arg0);
            return from_candid_CreatePaymentResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplications(): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplications();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplications();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitApplication(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: PayoutMethod): Promise<SubmitApplicationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApplication(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_PayoutMethod_n18(this._uploadFile, this._downloadFile, arg6));
                return from_candid_SubmitApplicationResult_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApplication(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_PayoutMethod_n18(this._uploadFile, this._downloadFile, arg6));
            return from_candid_SubmitApplicationResult_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updatePayoutStatus(arg0: string, arg1: string, arg2: Variant_pending_completed_processing): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayoutStatus(arg0, arg1, to_candid_variant_n22(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayoutStatus(arg0, arg1, to_candid_variant_n22(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_Application_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_CreatePaymentResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreatePaymentResult): CreatePaymentResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutMethod_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutMethod): PayoutMethod {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitApplicationResult_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitApplicationResult): SubmitApplicationResult {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    payoutStatus: {
        pending: null;
    } | {
        completed: null;
    } | {
        processing: null;
    };
    payoutMethod: _PayoutMethod;
    name: string;
    whatsapp: string;
    submittedAt: bigint;
    email: string;
    message: string;
    position: string;
    paymentIntentId: string;
}): {
    payoutStatus: Variant_pending_completed_processing;
    payoutMethod: PayoutMethod;
    name: string;
    whatsapp: string;
    submittedAt: bigint;
    email: string;
    message: string;
    position: string;
    paymentIntentId: string;
} {
    return {
        payoutStatus: from_candid_variant_n8(_uploadFile, _downloadFile, value.payoutStatus),
        payoutMethod: from_candid_PayoutMethod_n9(_uploadFile, _downloadFile, value.payoutMethod),
        name: value.name,
        whatsapp: value.whatsapp,
        submittedAt: value.submittedAt,
        email: value.email,
        message: value.message,
        position: value.position,
        paymentIntentId: value.paymentIntentId
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    btc: {
        address: string;
    };
} | {
    giftCard: {
        cardType: string;
        email: string;
    };
} | {
    paypal: {
        email: string;
    };
}): {
    __kind__: "btc";
    btc: {
        address: string;
    };
} | {
    __kind__: "giftCard";
    giftCard: {
        cardType: string;
        email: string;
    };
} | {
    __kind__: "paypal";
    paypal: {
        email: string;
    };
} {
    return "btc" in value ? {
        __kind__: "btc",
        btc: value.btc
    } : "giftCard" in value ? {
        __kind__: "giftCard",
        giftCard: value.giftCard
    } : "paypal" in value ? {
        __kind__: "paypal",
        paypal: value.paypal
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n16(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    submissionError: string;
} | {
    duplicateApplication: null;
} | {
    paymentNotFound: null;
} | {
    missingFields: null;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "submissionError";
    submissionError: string;
} | {
    __kind__: "duplicateApplication";
    duplicateApplication: null;
} | {
    __kind__: "paymentNotFound";
    paymentNotFound: null;
} | {
    __kind__: "missingFields";
    missingFields: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "submissionError" in value ? {
        __kind__: "submissionError",
        submissionError: value.submissionError
    } : "duplicateApplication" in value ? {
        __kind__: "duplicateApplication",
        duplicateApplication: value.duplicateApplication
    } : "paymentNotFound" in value ? {
        __kind__: "paymentNotFound",
        paymentNotFound: value.paymentNotFound
    } : "missingFields" in value ? {
        __kind__: "missingFields",
        missingFields: value.missingFields
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        clientSecret: string;
    };
} | {
    paymentError: string;
} | {
    invalidAmount: null;
}): {
    __kind__: "ok";
    ok: {
        clientSecret: string;
    };
} | {
    __kind__: "paymentError";
    paymentError: string;
} | {
    __kind__: "invalidAmount";
    invalidAmount: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "paymentError" in value ? {
        __kind__: "paymentError",
        paymentError: value.paymentError
    } : "invalidAmount" in value ? {
        __kind__: "invalidAmount",
        invalidAmount: value.invalidAmount
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    processing: null;
}): Variant_pending_completed_processing {
    return "pending" in value ? Variant_pending_completed_processing.pending : "completed" in value ? Variant_pending_completed_processing.completed : "processing" in value ? Variant_pending_completed_processing.processing : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n6(_uploadFile, _downloadFile, x));
}
function to_candid_PayoutMethod_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PayoutMethod): _PayoutMethod {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "btc";
    btc: {
        address: string;
    };
} | {
    __kind__: "giftCard";
    giftCard: {
        cardType: string;
        email: string;
    };
} | {
    __kind__: "paypal";
    paypal: {
        email: string;
    };
}): {
    btc: {
        address: string;
    };
} | {
    giftCard: {
        cardType: string;
        email: string;
    };
} | {
    paypal: {
        email: string;
    };
} {
    return value.__kind__ === "btc" ? {
        btc: value.btc
    } : value.__kind__ === "giftCard" ? {
        giftCard: value.giftCard
    } : value.__kind__ === "paypal" ? {
        paypal: value.paypal
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed_processing): {
    pending: null;
} | {
    completed: null;
} | {
    processing: null;
} {
    return value == Variant_pending_completed_processing.pending ? {
        pending: null
    } : value == Variant_pending_completed_processing.completed ? {
        completed: null
    } : value == Variant_pending_completed_processing.processing ? {
        processing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
